#!/usr/bin/env bash
set -euo pipefail

# Publish a Go CLI from a private local source repo as a public binary
# release on this tap.
#
#   ./release-cli.sh <tool> <version>        e.g. ./release-cli.sh dotrun 0.1.0
#
# What it does, in order:
#   1. refuses to run if the tool's source tree is dirty
#   2. runs the tool's test suite
#   3. builds darwin arm64 + amd64 with leak-safe flags (see BUILD FLAGS)
#   4. tars each bare binary from an empty temp dir (nothing else can ride along)
#   5. regenerates Formula/<tool>.rb from the template below (no sed-patching)
#   6. commits the formula, pushes, creates GitHub release <tool>-v<version>
#      on this tap repo with the two tarballs as assets
#
# The source repos stay private; the ONLY public artifacts are the two
# binary tarballs, the formula text, and the release notes written here.
#
# BUILD FLAGS — load-bearing for not leaking information:
#   -trimpath        no absolute build-machine paths in the binary
#   -buildvcs=false  no source-repo commit hash / timestamp / dirty flag
#   -ldflags -s -w   strip symbol + debug tables
#   CGO_ENABLED=0    pure-Go static binary, no local toolchain fingerprints
# Audited 2026-06-11: with these flags, `strings` output for agent-lock and
# dotrun contains no home paths, emails, hostnames, or credentials.

TOOL="${1:?usage: release-cli.sh <tool> <version>}"
VERSION="${2:?usage: release-cli.sh <tool> <version>}"
REPO="yifanzz/homebrew-tap"
TAP_DIR="$(cd "$(dirname "$0")" && pwd)"

# Per-tool registry: source dir + formula description.
# Adding a tool to the tap = adding a case branch here.
case "$TOOL" in
  agent-lock)
    SRC="$HOME/code/agent-queue"
    DESC="Repo-level mutex that stops concurrent AI coding agents editing the same repo"
    ;;
  dotrun)
    SRC="$HOME/code/dotrun"
    DESC="Load .env files and run a command (dotenv-cli compatible)"
    ;;
  *)
    echo "unknown tool: $TOOL (add it to the case table in $0)" >&2
    exit 1
    ;;
esac

[[ -d "$SRC/.git" ]] || { echo "source dir $SRC is not a git repo" >&2; exit 1; }
if [[ -n "$(git -C "$SRC" status --porcelain)" ]]; then
  echo "refusing to release: $SRC has uncommitted changes" >&2
  exit 1
fi

echo "==> Testing $TOOL"
(cd "$SRC" && go test ./...)

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

declare -a SHAS=()
for ARCH in arm64 amd64; do
  echo "==> Building $TOOL $VERSION darwin/$ARCH"
  OUT="$STAGE/$ARCH"
  mkdir -p "$OUT"
  (cd "$SRC" && CGO_ENABLED=0 GOOS=darwin GOARCH="$ARCH" \
    go build -trimpath -buildvcs=false -ldflags="-s -w" -o "$OUT/$TOOL" .)
  tar -czf "$STAGE/$TOOL-$VERSION-darwin-$ARCH.tar.gz" -C "$OUT" "$TOOL"
  SHAS+=("$(shasum -a 256 "$STAGE/$TOOL-$VERSION-darwin-$ARCH.tar.gz" | cut -d' ' -f1)")
done
SHA_ARM64="${SHAS[0]}"
SHA_AMD64="${SHAS[1]}"

# agent-lock -> AgentLock
CLASS="$(echo "$TOOL" | awk -F- '{for (i=1; i<=NF; i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2)}')"

mkdir -p "$TAP_DIR/Formula"
cat > "$TAP_DIR/Formula/$TOOL.rb" <<EOF
# Generated by release-cli.sh — do not edit by hand; edit the template there.
class $CLASS < Formula
  desc "$DESC"
  homepage "https://github.com/$REPO"
  version "$VERSION"

  on_macos do
    on_arm do
      url "https://github.com/$REPO/releases/download/$TOOL-v#{version}/$TOOL-#{version}-darwin-arm64.tar.gz"
      sha256 "$SHA_ARM64"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/$TOOL-v#{version}/$TOOL-#{version}-darwin-amd64.tar.gz"
      sha256 "$SHA_AMD64"
    end
  end

  def install
    bin.install "$TOOL"
  end

  test do
    system "#{bin}/$TOOL", "--help"
  end
end
EOF

echo "==> Committing formula"
git -C "$TAP_DIR" add "Formula/$TOOL.rb"
git -C "$TAP_DIR" commit -m "Publish $TOOL $VERSION"
git -C "$TAP_DIR" push

echo "==> Creating release $TOOL-v$VERSION"
gh release create "$TOOL-v$VERSION" \
  --repo "$REPO" \
  --title "$TOOL $VERSION" \
  --notes "$TOOL $VERSION (darwin arm64 + amd64). Binary-only release; source is private." \
  "$STAGE/$TOOL-$VERSION-darwin-arm64.tar.gz" \
  "$STAGE/$TOOL-$VERSION-darwin-amd64.tar.gz"

echo "==> Done: brew install $REPO/$TOOL"
