# Generated by release-cli.sh — do not edit by hand; edit the template there.
class AgentLock < Formula
  desc "Repo-level mutex that stops concurrent AI coding agents editing the same repo"
  homepage "https://github.com/yifanzz/homebrew-tap"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/yifanzz/homebrew-tap/releases/download/agent-lock-v#{version}/agent-lock-#{version}-darwin-arm64.tar.gz"
      sha256 "8b9c139018595d38cbf819a6aa491f002036bea0ca3bacd861e83f346ad49fd8"
    end
    on_intel do
      url "https://github.com/yifanzz/homebrew-tap/releases/download/agent-lock-v#{version}/agent-lock-#{version}-darwin-amd64.tar.gz"
      sha256 "1108b927d9f1a64ad341872d08656e6d78719bd787b711c68a60907143249a6e"
    end
  end

  def install
    bin.install "agent-lock"
  end

  test do
    system "#{bin}/agent-lock", "--help"
  end
end
