# Generated by release-cli.sh — do not edit by hand; edit the template there.
class Dotrun < Formula
  desc "Load .env files and run a command (dotenv-cli compatible)"
  homepage "https://github.com/yifanzz/homebrew-tap"
  version "0.4.0"

  on_macos do
    on_arm do
      url "https://github.com/yifanzz/homebrew-tap/releases/download/dotrun-v#{version}/dotrun-#{version}-darwin-arm64.tar.gz"
      sha256 "96bac336b18fe0caf22ab7557bcc42aa0b4d542b900023fc1cd2b7c1fc145240"
    end
    on_intel do
      url "https://github.com/yifanzz/homebrew-tap/releases/download/dotrun-v#{version}/dotrun-#{version}-darwin-amd64.tar.gz"
      sha256 "dc72c0dddf441c0ee724b2c1304179a8faf851ecec8c80aad7e4b3c27910da0c"
    end
  end

  def install
    bin.install "dotrun"
    bin.install_symlink "dotrun" => "dotrun-shell"
  end

  test do
    system "#{bin}/dotrun", "--help"
  end
end
