# Generated by release-cli.sh — do not edit by hand; edit the template there.
class Dotrun < Formula
  desc "Load .env files and run a command (dotenv-cli compatible)"
  homepage "https://github.com/yifanzz/homebrew-tap"
  version "0.4.1"

  on_macos do
    on_arm do
      url "https://github.com/yifanzz/homebrew-tap/releases/download/dotrun-v#{version}/dotrun-#{version}-darwin-arm64.tar.gz"
      sha256 "4f2e8a8d854a31091663c2c15d3738ae65e6ca4488928312661d95960694a678"
    end
    on_intel do
      url "https://github.com/yifanzz/homebrew-tap/releases/download/dotrun-v#{version}/dotrun-#{version}-darwin-amd64.tar.gz"
      sha256 "590857d57f5d6478cbb7c7efe244651296a3b5f773d82ff0dad69cee0f42303f"
    end
  end

  def install
    bin.install "dotrun"
    bin.install_symlink "dotrun" => "dotrun-shell"
  end

  test do
    system "#{bin}/dotrun", "--help"
  end
end
